baseURL: https://fazledyn.github.io

languageCode: en

title: Ataf Fazledin Ahamed

copyright: © Copyright 2024 Ataf Fazledin Ahamed

theme: academic-folio

enableEmoji: true

enableRobotsTXT: true

publishDir: "../docs/"

markup:
  highlight:
    guessSyntax: true
    style: dracula  # syntax highlighting style for markdown code blocks
                    # choose a style from https://xyproto.github.io/splash/docs/all.html

module:
  imports:
  - path: github.com/FortAwesome/Font-Awesome
    mounts:
    - source: svgs
      target: assets/svgs/fontawesome
